name: "CI"

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Code Formatting
        run: |
          cargo fmt --all --check

      - name: Check Code With Clippy
        run: |
          cargo clippy

  check-docker-build:
    name: Check Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v3

      - name: Check Docker Build
        run: docker build .

  test-docker-builder:
    name: Test Docker Builder
    runs-on: ubuntu-latest
    needs: check-docker-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t builder .

      - name: Run Test Build in Docker
        run: |
          docker run -v "$(pwd)/test-program:/app" --entrypoint /bin/bash builder -c 'cargo build --release'

      - name: Verify Build Output
        run: |
          if [ ! -f test-program/target/wasm32-gear/release/ping_pong.opt.wasm ]; then
            echo "Error: Expected WASM file not found"
            exit 1
          else
            echo "Success: WASM file found"
          fi

  test-openapi-spec:
    name: Test openapi spec
    runs-on: ubuntu-latest
    needs: check-docker-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test
