name: "CI"

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Code Formatting
        run: |
          cargo fmt --all --check

      - name: Check Code With Clippy
        run: |
          cargo clippy
